### ISSUE TITLE
Server doesn't always receive all the data

### ISSUE THREAD

**Issue by snopoke** [greyside/errand-boy#1]
Firstly, great tool, thanks!

I'm having an intermittent issue where the server doesn't receive all the data sent by the client. I've added a check that prints out when this happens in my fork: https://github.com/greyside/errand-boy/compare/master...snopoke:receive

I've also created a test file: https://gist.github.com/snopoke/34404c5eea460db7f5ac

It doesn't fail every time but probably about 60% of the time with the following output (when it does fails it always fails in the same way):
```
length mismatch 244544 219195
```

The result of not reading all the data is that `pickle.loads` hangs.

I'd really like to use this tool but can't until I can get this fixed.

**Comment by SeanHayes** [comment]
Do you know if it only happens during a certain part of your script?

communicate() already waits for the process to terminate, so calling wait() after that might lead to odd behavior. Try this instead:

    exit_code = p.returncode

That's what I've done in my projects and haven't had any trouble.

I'll try your test script tomorrow.

**Comment by snopoke** [comment]
Thanks for looking into this.

Yes, its always happens at the call to `communicate`. I have tried getting rid of the `wait` but that didn't help. I think it has to do with the size of the data that is being piped to the process. If I reduce the amount of data to below the `219195` limit then it never fails.

**Comment by SeanHayes** [comment]
"echo" only accepts input from the command line, not from stdin, so I changed the command to "cat". I was then able to reproduce and fix the issue.

The issue was receiving data from a socket sometimes returns less data than requested and another read operation needs to be performed, but my code assumed it would block until the requested length was returned.

**Comment by snopoke** [comment]
Thanks! So frustrating though since I tried a similar approach that didn't work.
