### ISSUE TITLE
stdin

### ISSUE THREAD

**Issue by JohnLonginotto** [greyside/errand-boy#3]
Can errand-boy spawn a subprocess that can have data written to it via stdin?Can errand-boy spawn a subprocess that can have data written to it via stdin?

**Comment by SeanHayes** [comment]
Yes! Use the following:

```
with errand_boy_transport.get_session() as session:
    subprocess = session.subprocess
```

and use the `subprocess` variable within that `with` block the same way you would the `subprocess` module.

**Comment by SeanHayes** [comment]
Let me know if you have any more questions.

**Comment by JohnLonginotto** [comment]
Awws hells yeah! No more need to spawn 650 processes at the beginning of my script. Thank you for basically fixing Linux :P

**Comment by SeanHayes** [comment]
To be clear, errand-boy itself maintains the pool of processes, which themselves will fork in order to run whatever you tell `subprocess.Popen` to. Hopefully this solves any memory issues you may have been having.

**Comment by JohnLonginotto** [comment]
It does :) Works totally perfect - thanks a million man :)
