### ISSUE TITLE
"error: [Errno 2] No such file or directory" when using `run_cmd`

### ISSUE THREAD

**Issue by yingkaisha** [greyside/errand-boy#4]
I found the package by searching solutions on `subprocess.Popen()` out of memory. Basically I have some shell cmds to run in Python scripts, like `'./XX.exe'`, `rm *.txt`, `'mkdir -p XX/XXX'`.

Maybe I didn't understand it right, but when I was testing the example, I got the following error:  

```python
In [1]: from errand_boy.transports.unixsocket import UNIXSocketTransport

In [2]: errand_boy_transport = UNIXSocketTransport()

In [3]: errand_boy_transport.run_cmd('ls')
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-3-c7aa72265fc5> in <module>()
----> 1 errand_boy_transport.run_cmd('ls')

/home/XXXXX/anaconda2/lib/python2.7/site-packages/errand_boy/transports/base.pyc in run_cmd(self, command_string)
    437
    438     def run_cmd(self, command_string):
--> 439         with self.get_session() as session:
    440             subprocess = session.subprocess
    441

/home/XXXXX/anaconda2/lib/python2.7/site-packages/errand_boy/transports/base.pyc in get_session(self)
    434
    435     def get_session(self):
--> 436         return ClientSession(self)
    437
    438     def run_cmd(self, command_string):

/home/XXXXX/anaconda2/lib/python2.7/site-packages/errand_boy/transports/base.pyc in __init__(self, transport)
     29     def __init__(self, transport):
     30         self.transport = transport
---> 31         self.connection = transport.client_get_connection()
     32         self._closed = True
     33

/home/XXXXX/anaconda2/lib/python2.7/site-packages/errand_boy/transports/unixsocket.pyc in client_get_connection(self)
     81         clientsocket = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
     82
---> 83         clientsocket.connect(self.socket_path)
     84
     85         return clientsocket

/home/XXXXX/anaconda2/lib/python2.7/socket.pyc in meth(name, self, *args)
    226
    227 def meth(name,self,*args):
--> 228     return getattr(self._sock,name)(*args)
    229
    230 for _m in _socketmethods:

error: [Errno 2] No such file or directory
```

As you can see I'm in Anaconda Python 2.7, the package was installed by `pip`

Does anyone knows how to deal with the problem ? 

Thanks

**Comment by SeanHayes** [comment]
You mentioned one of the file types was .exe, are you running this on WIndows? This library and the problem it solves is Unix/Unix-like specific.

**Comment by SeanHayes** [comment]
If you are on a Unix-like system, that error means the unix socket either doesn't exist or isn't visible to the process for some other reason.

**Comment by SeanHayes** [comment]
Wait, this error is happening in the client code. Is the server running in a separate process? The server should create the unix socket.

**Comment by yingkaisha** [comment]
No it is in UNIX. Sorry I don't know much about your comment later. I ssh-ed to a cluster from remote and things were tested there.

**Comment by SeanHayes** [comment]
To clarify: an errand-boy server process needs to be running on the same machine as the client in order for the client to work. This server process most likely uses less memory than your application, which is how it avoids the out of memory error when the process fork happens.

**Comment by yingkaisha** [comment]
So errand-boy cannot work in ssh ?

**Comment by SeanHayes** [comment]
It can. You'll have to start the server process in the background before the client can do anything though.

**Comment by yingkaisha** [comment]
I see , I missed "python -m errand_boy.run &". Now I think it works. Thank you so much.
