### ISSUE TITLE
Programatically start server?

### ISSUE THREAD

**Issue by aidangomez** [greyside/errand-boy#5]
Is there any way for me to start the required server from my module when it is imported? I.e I don't want to have to run `python -m errand_boy.run` before calling my script, I just want there to be a process started as soon as my package is imported by someone.

Thanks for the help

**Comment by SeanHayes** [comment]
You could always use `subprocess.Popen()`. You can also import the function that gets called by `python -m errand_boy.run`:
```
from errand_boy.run import main

main()
```
